### ISSUE TITLE
Request: Include tracking of Raspberry Pi stats

### ISSUE THREAD

**Issue by Griefed** [RafhaanShah/grAfterburner#2]
Hello RafhaanShah,

would it be possible to track the Raspberry Pi temperature in addition to everything else, so one could add a gauge for the Pi's temp?
Maybe expand the idea so memory usage and cpu usage of the Pi is tracked as well. Having one Dashboard that displays all of the data provided by the MSI Remote Server and the stats of the Raspberry Pi on which this runs on, would be awesome.

I hope that's possible.
Thanks for your time and thanks for all your effort!

Cheers,
Griefed

**Comment by RafhaanShah** [comment]
Hey!

Should be pretty easy by adding a couple more plugins to the `collectd.conf` file.

```
LoadPlugin thermal
LoadPlugin memory
LoadPlugin cpu

<Plugin thermal>
</Plugin>

<Plugin memory>
    ValuesAbsolute false
    ValuesPercentage true
</Plugin>

<Plugin cpu>
    ReportByState false
    ReportByCpu false
</Plugin>
```

You can then just edit the dashboards to add your new measurements.

Have a look at the docs for collectd to see what else it can do!
https://collectd.org/documentation/manpages/collectd.conf.5.shtml
