### ISSUE TITLE
sometimes get "Connected to MSI Afterburner shared memory that is flagged as dead"

### ISSUE THREAD

**Issue by moz-uk** [RafhaanShah/grAfterburner#5]
from remote afterburner server

```
<error>
<message>Connected to MSI Afterburner shared memory that is flagged as dead.</message>
</error>
```

**Comment by moz-uk** [comment]
obviously an afterburner remote server issue, any idea how to clear without a reboot? think i added something to the afterburner monitor this time when it broke, have tried restarting afterburner/rtss etc

**Comment by RafhaanShah** [comment]
Kill afterburner and remote server and start afterburner first before the remote server
